import type {
  FantasyPlayer,
  FantasyTeam,
  LeagueData,
  Matchup,
  LiveStatSnapshot,
  PlayerRole,
} from "@/lib/types";

function p(
  partial: Omit<FantasyPlayer, "id"> & { id?: string },
): FantasyPlayer {
  return {
    id: partial.id ?? `p-${partial.espnId}`,
    ...partial,
  };
}

const DEMO_ROSTER_SEBASTIAN: FantasyPlayer[] = [
  p({
    espnId: 3918298,
    name: "Josh Allen",
    position: "QB",
    nflTeam: "BUF",
    injuryStatus: "ACTIVE",
    projectedPoints: 22.4,
    actualPoints: 18.6,
    percentOwned: 99.8,
    percentStarted: 97.2,
    opponent: "@ MIA",
    slot: "QB",
    isStarter: true,
    role: "qb",
    recentWeeks: [
      { week: 4, points: 28.4, opponent: "@ BAL" },
      { week: 5, points: 19.2, opponent: "vs HOU" },
      { week: 6, points: 24.1, opponent: "@ NYJ" },
    ],
  }),
  p({
    espnId: 4429795,
    name: "Breece Hall",
    position: "RB",
    nflTeam: "NYJ",
    injuryStatus: "QUESTIONABLE",
    projectedPoints: 14.8,
    actualPoints: 0,
    percentOwned: 98.1,
    percentStarted: 82.4,
    opponent: "vs NE",
    slot: "RB",
    isStarter: true,
    role: "rb1",
    recentWeeks: [
      { week: 4, points: 11.2, opponent: "vs DEN" },
      { week: 5, points: 16.8, opponent: "@ MIN" },
      { week: 6, points: 8.4, opponent: "vs BUF" },
    ],
  }),
  p({
    espnId: 4430807,
    name: "Jahmyr Gibbs",
    position: "RB",
    nflTeam: "DET",
    injuryStatus: "ACTIVE",
    projectedPoints: 16.2,
    actualPoints: 21.4,
    percentOwned: 99.2,
    percentStarted: 94.1,
    opponent: "@ GB",
    slot: "RB",
    isStarter: true,
    role: "rb1",
    recentWeeks: [
      { week: 4, points: 22.6, opponent: "vs SEA" },
      { week: 5, points: 14.1, opponent: "@ DAL" },
      { week: 6, points: 18.9, opponent: "vs CIN" },
    ],
  }),
  p({
    espnId: 4362626,
    name: "CeeDee Lamb",
    position: "WR",
    nflTeam: "DAL",
    injuryStatus: "ACTIVE",
    projectedPoints: 15.9,
    actualPoints: 12.3,
    percentOwned: 99.5,
    percentStarted: 96.0,
    opponent: "vs NYG",
    slot: "WR",
    isStarter: true,
    role: "wr_outside",
    recentWeeks: [
      { week: 4, points: 9.8, opponent: "@ NYG" },
      { week: 5, points: 17.4, opponent: "vs PIT" },
      { week: 6, points: 11.2, opponent: "vs DET" },
    ],
  }),
  p({
    espnId: 4426385,
    name: "Amon-Ra St. Brown",
    position: "WR",
    nflTeam: "DET",
    injuryStatus: "ACTIVE",
    projectedPoints: 14.1,
    actualPoints: 17.8,
    percentOwned: 99.0,
    percentStarted: 93.5,
    opponent: "@ GB",
    slot: "WR",
    isStarter: true,
    role: "wr_slot",
    recentWeeks: [
      { week: 4, points: 15.2, opponent: "vs SEA" },
      { week: 5, points: 8.1, opponent: "@ DAL" },
      { week: 6, points: 19.6, opponent: "vs CIN" },
    ],
  }),
  p({
    espnId: 3117251,
    name: "Travis Kelce",
    position: "TE",
    nflTeam: "KC",
    injuryStatus: "ACTIVE",
    projectedPoints: 11.2,
    actualPoints: 8.4,
    percentOwned: 97.4,
    percentStarted: 88.2,
    opponent: "vs LV",
    slot: "TE",
    isStarter: true,
    role: "te",
    recentWeeks: [
      { week: 4, points: 7.2, opponent: "@ LAC" },
      { week: 5, points: 12.8, opponent: "vs NO" },
      { week: 6, points: 6.4, opponent: "@ SF" },
    ],
  }),
  p({
    espnId: 4430878,
    name: "Puka Nacua",
    position: "WR",
    nflTeam: "LAR",
    injuryStatus: "OUT",
    projectedPoints: 13.6,
    actualPoints: 9.1,
    percentOwned: 98.6,
    percentStarted: 79.0,
    opponent: "@ SEA",
    slot: "FLEX",
    isStarter: true,
    role: "wr_outside",
    recentWeeks: [
      { week: 4, points: 14.6, opponent: "vs CHI" },
      { week: 5, points: 10.2, opponent: "@ SF" },
      { week: 6, points: 18.1, opponent: "vs ARI" },
    ],
  }),
  p({
    espnId: 3051890,
    name: "Harrison Butker",
    position: "K",
    nflTeam: "KC",
    injuryStatus: "ACTIVE",
    projectedPoints: 8.5,
    actualPoints: 7.0,
    percentOwned: 72.0,
    percentStarted: 65.0,
    opponent: "vs LV",
    slot: "K",
    isStarter: true,
    role: "k",
  }),
  p({
    espnId: -16002,
    name: "Bills D/ST",
    position: "D/ST",
    nflTeam: "BUF",
    injuryStatus: "ACTIVE",
    projectedPoints: 7.8,
    actualPoints: 11.0,
    percentOwned: 68.0,
    percentStarted: 55.0,
    opponent: "@ MIA",
    slot: "D/ST",
    isStarter: true,
    role: "dst",
  }),
  p({
    espnId: 4427366,
    name: "Jayden Reed",
    position: "WR",
    nflTeam: "GB",
    injuryStatus: "ACTIVE",
    projectedPoints: 10.4,
    actualPoints: 0,
    percentOwned: 54.0,
    percentStarted: 18.0,
    opponent: "vs DET",
    slot: "BN",
    isStarter: false,
    role: "wr_slot",
    recentWeeks: [
      { week: 4, points: 12.4, opponent: "vs MIN" },
      { week: 5, points: 4.1, opponent: "@ CLE" },
      { week: 6, opponent: "vs ARI", points: 11.8 },
    ],
  }),
  p({
    espnId: 4241389,
    name: "Zack Moss",
    position: "RB",
    nflTeam: "CIN",
    injuryStatus: "OUT",
    projectedPoints: 0,
    actualPoints: 0,
    percentOwned: 22.0,
    percentStarted: 1.2,
    opponent: "@ BAL",
    slot: "BN",
    isStarter: false,
    role: "rb2",
  }),
  p({
    espnId: 4569618,
    name: "Rome Odunze",
    position: "WR",
    nflTeam: "CHI",
    injuryStatus: "ACTIVE",
    projectedPoints: 9.8,
    actualPoints: 0,
    percentOwned: 61.0,
    percentStarted: 22.0,
    opponent: "vs IND",
    slot: "BN",
    isStarter: false,
    role: "wr_outside",
    recentWeeks: [
      { week: 4, points: 8.6, opponent: "@ LAR" },
      { week: 5, points: 13.2, opponent: "vs CAR" },
      { week: 6, points: 3.4, opponent: "@ CLE" },
    ],
  }),
  p({
    espnId: 3916387,
    name: "Baker Mayfield",
    position: "QB",
    nflTeam: "TB",
    injuryStatus: "ACTIVE",
    projectedPoints: 17.1,
    actualPoints: 0,
    percentOwned: 48.0,
    percentStarted: 21.0,
    opponent: "@ ATL",
    slot: "BN",
    isStarter: false,
    role: "qb",
    recentWeeks: [
      { week: 4, points: 21.2, opponent: "vs PHI" },
      { week: 5, points: 16.8, opponent: "@ SEA" },
      { week: 6, points: 19.4, opponent: "vs NO" },
    ],
  }),
  p({
    espnId: 4432708,
    name: "Trey Benson",
    position: "RB",
    nflTeam: "ARI",
    injuryStatus: "ACTIVE",
    projectedPoints: 6.2,
    actualPoints: 0,
    percentOwned: 18.0,
    percentStarted: 2.0,
    opponent: "vs SF",
    slot: "BN",
    isStarter: false,
    role: "rb2",
    recentWeeks: [
      { week: 5, points: 4.2, opponent: "@ SF" },
      { week: 6, points: 7.8, opponent: "vs GB" },
    ],
  }),
];

function buildTeam(
  id: number,
  name: string,
  abbrev: string,
  owner: string,
  standing: number,
  record: [number, number, number],
  pf: number,
  pa: number,
  roster: FantasyPlayer[],
  isCurrentUser = false,
): FantasyTeam {
  return {
    id,
    name,
    abbrev,
    ownerName: owner,
    wins: record[0],
    losses: record[1],
    ties: record[2],
    pointsFor: pf,
    pointsAgainst: pa,
    standing,
    roster,
    isCurrentUser,
  };
}

function stubRoster(seed: number): FantasyPlayer[] {
  const names = [
    ["Patrick Mahomes", "QB", "KC"],
    ["Saquon Barkley", "RB", "PHI"],
    ["Derrick Henry", "RB", "BAL"],
    ["Tyreek Hill", "WR", "MIA"],
    ["Ja'Marr Chase", "WR", "CIN"],
    ["Mark Andrews", "TE", "BAL"],
    ["Davante Adams", "WR", "NYJ"],
    ["Justin Tucker", "K", "BAL"],
    ["Ravens D/ST", "D/ST", "BAL"],
    ["James Conner", "RB", "ARI"],
    ["Christian Watson", "WR", "GB"],
    ["Tua Tagovailoa", "QB", "MIA"],
  ] as const;

  return names.map((n, i) =>
    p({
      espnId: 900000 + seed * 100 + i,
      name: n[0],
      position: n[1] as FantasyPlayer["position"],
      nflTeam: n[2],
      injuryStatus:
        seed === 2 && n[0] === "Saquon Barkley"
          ? "OUT"
          : seed === 3 && n[0] === "Tua Tagovailoa"
            ? "OUT"
            : i === 10
              ? "QUESTIONABLE"
              : "ACTIVE",
      projectedPoints: 8 + ((seed + i) % 12) + i * 0.3,
      actualPoints: i < 9 ? 6 + ((seed * 3 + i * 2) % 18) : 0,
      percentOwned: 40 + ((seed + i * 7) % 55),
      percentStarted: 20 + ((seed + i * 5) % 70),
      opponent: i % 2 === 0 ? "vs CLE" : "@ DEN",
      slot: (i < 9
        ? (["QB", "RB", "RB", "WR", "WR", "TE", "FLEX", "K", "D/ST"] as const)[i]
        : "BN") as FantasyPlayer["slot"],
      isStarter: i < 9,
    }),
  );
}

export function createDemoLeague(userTeamId = 1): LeagueData {
  const teams: FantasyTeam[] = [
    buildTeam(
      1,
      "Sebastian's Squad",
      "SEB",
      "Sebastian",
      2,
      [4, 2, 0],
      742.4,
      698.1,
      DEMO_ROSTER_SEBASTIAN,
      true,
    ),
    buildTeam(2, "Gridiron Gurus", "GG", "Alex", 1, [5, 1, 0], 781.2, 650.4, stubRoster(2)),
    buildTeam(3, "End Zone Elite", "EZE", "Jordan", 3, [4, 2, 0], 720.8, 705.2, stubRoster(3)),
    buildTeam(4, "Blitz Brigade", "BB", "Sam", 4, [3, 3, 0], 690.1, 712.0, stubRoster(4)),
    buildTeam(5, "Red Zone Raiders", "RZR", "Casey", 5, [3, 3, 0], 668.5, 701.4, stubRoster(5)),
    buildTeam(6, "Fourth & Long", "F4L", "Riley", 6, [2, 4, 0], 640.2, 730.8, stubRoster(6)),
    buildTeam(7, "Hail Mary FC", "HMF", "Morgan", 7, [2, 4, 0], 612.9, 745.1, stubRoster(7)),
    buildTeam(8, "Sack Exchange", "SACK", "Taylor", 8, [1, 5, 0], 580.4, 772.3, stubRoster(8)),
  ].map((t) => ({ ...t, isCurrentUser: t.id === userTeamId }));

  // Situational injury demos for Waiver Wire Shark (documented statuses only).
  const team2 = teams.find((t) => t.id === 2);
  if (team2) {
    const kyrenIdx = team2.roster.findIndex((p) => p.position === "RB" && p.isStarter);
    if (kyrenIdx >= 0) {
      team2.roster[kyrenIdx] = p({
        espnId: 4430802,
        name: "Kyren Williams",
        position: "RB",
        nflTeam: "LAR",
        injuryStatus: "OUT",
        projectedPoints: 0,
        actualPoints: 0,
        percentOwned: 97.0,
        percentStarted: 90.0,
        opponent: "@ SEA",
        slot: team2.roster[kyrenIdx].slot,
        isStarter: true,
        role: "rb1",
      });
    }
  }
  const team3 = teams.find((t) => t.id === 3);
  if (team3) {
    const qbIdx = team3.roster.findIndex((p) => p.position === "QB" && p.isStarter);
    if (qbIdx >= 0) {
      team3.roster[qbIdx] = {
        ...team3.roster[qbIdx],
        name: "Tua Tagovailoa",
        espnId: 4241479,
        nflTeam: "MIA",
        injuryStatus: "OUT",
        projectedPoints: 0,
        role: "qb",
      };
    }
  }


  const matchups: Matchup[] = [
    {
      id: 1,
      week: 7,
      homeTeamId: 1,
      awayTeamId: 4,
      homeScore: 98.4,
      awayScore: 91.2,
      homeProjected: 112.6,
      awayProjected: 104.1,
      isLive: true,
    },
    {
      id: 2,
      week: 7,
      homeTeamId: 2,
      awayTeamId: 5,
      homeScore: 105.1,
      awayScore: 88.0,
      homeProjected: 118.2,
      awayProjected: 99.4,
      isLive: true,
    },
    {
      id: 3,
      week: 7,
      homeTeamId: 3,
      awayTeamId: 6,
      homeScore: 76.3,
      awayScore: 82.7,
      homeProjected: 108.0,
      awayProjected: 101.5,
      isLive: true,
    },
    {
      id: 4,
      week: 7,
      homeTeamId: 7,
      awayTeamId: 8,
      homeScore: 64.0,
      awayScore: 71.5,
      homeProjected: 95.2,
      awayProjected: 92.8,
      isLive: true,
    },
  ];

  const freeAgents: FantasyPlayer[] = [
    p({
      espnId: 3915416,
      name: "Tutu Atwell",
      position: "WR",
      nflTeam: "LAR",
      injuryStatus: "ACTIVE",
      projectedPoints: 10.4,
      actualPoints: 0,
      percentOwned: 14.0,
      percentStarted: 3.0,
      opponent: "@ SEA",
      role: "wr_outside",
    }),
    p({
      espnId: 4429020,
      name: "Blake Corum",
      position: "RB",
      nflTeam: "LAR",
      injuryStatus: "ACTIVE",
      projectedPoints: 9.2,
      actualPoints: 0,
      percentOwned: 22.0,
      percentStarted: 5.0,
      opponent: "@ SEA",
      role: "rb2",
    }),
    p({
      espnId: 2969939,
      name: "Jameis Winston",
      position: "QB",
      nflTeam: "MIA",
      injuryStatus: "ACTIVE",
      projectedPoints: 14.8,
      actualPoints: 0,
      percentOwned: 6.0,
      percentStarted: 1.0,
      opponent: "vs BUF",
      role: "qb",
    }),

    p({
      espnId: 4241479,
      name: "Tank Dell",
      position: "WR",
      nflTeam: "HOU",
      injuryStatus: "ACTIVE",
      projectedPoints: 11.2,
      actualPoints: 0,
      percentOwned: 42.0,
      percentStarted: 12.0,
      opponent: "@ NE",
    }),
    p({
      espnId: 4429013,
      name: "Rico Dowdle",
      position: "RB",
      nflTeam: "DAL",
      injuryStatus: "ACTIVE",
      projectedPoints: 10.8,
      actualPoints: 0,
      percentOwned: 38.0,
      percentStarted: 15.0,
      opponent: "vs NYG",
    }),
    p({
      espnId: 4360238,
      name: "Jalen Tolbert",
      position: "WR",
      nflTeam: "DAL",
      injuryStatus: "ACTIVE",
      projectedPoints: 8.4,
      actualPoints: 0,
      percentOwned: 12.0,
      percentStarted: 2.0,
      opponent: "vs NYG",
    }),
    p({
      espnId: 4035687,
      name: "Courtland Sutton",
      position: "WR",
      nflTeam: "DEN",
      injuryStatus: "ACTIVE",
      projectedPoints: 10.1,
      actualPoints: 0,
      percentOwned: 55.0,
      percentStarted: 28.0,
      opponent: "vs LV",
    }),
    p({
      espnId: 3120348,
      name: "Tyler Higbee",
      position: "TE",
      nflTeam: "LAR",
      injuryStatus: "QUESTIONABLE",
      projectedPoints: 7.2,
      actualPoints: 0,
      percentOwned: 18.0,
      percentStarted: 4.0,
      opponent: "@ SEA",
    }),
    p({
      espnId: 4242433,
      name: "Bo Nix",
      position: "QB",
      nflTeam: "DEN",
      injuryStatus: "ACTIVE",
      projectedPoints: 16.8,
      actualPoints: 0,
      percentOwned: 45.0,
      percentStarted: 19.0,
      opponent: "vs LV",
    }),
    p({
      espnId: -16015,
      name: "Chiefs D/ST",
      position: "D/ST",
      nflTeam: "KC",
      injuryStatus: "ACTIVE",
      projectedPoints: 8.9,
      actualPoints: 0,
      percentOwned: 52.0,
      percentStarted: 40.0,
      opponent: "vs LV",
    }),
    p({
      espnId: 3055899,
      name: "Younghoe Koo",
      position: "K",
      nflTeam: "ATL",
      injuryStatus: "ACTIVE",
      projectedPoints: 8.1,
      actualPoints: 0,
      percentOwned: 28.0,
      percentStarted: 18.0,
      opponent: "vs TB",
    }),
    p({
      espnId: 4426388,
      name: "Roschon Johnson",
      position: "RB",
      nflTeam: "CHI",
      injuryStatus: "ACTIVE",
      projectedPoints: 5.4,
      actualPoints: 0,
      percentOwned: 8.0,
      percentStarted: 0.5,
      opponent: "vs IND",
    }),
    p({
      espnId: 4567048,
      name: "Marvin Harrison Jr.",
      position: "WR",
      nflTeam: "ARI",
      injuryStatus: "ACTIVE",
      projectedPoints: 12.6,
      actualPoints: 0,
      percentOwned: 88.0,
      percentStarted: 62.0,
      opponent: "vs SF",
    }),
  ];

  return {
    leagueId: "demo-league",
    season: Number(process.env.DEFAULT_ESPN_SEASON ?? 2025),
    name: "Sebastian's Demo League",
    currentWeek: 7,
    scoringPeriodId: 7,
    isDemo: true,
    teams,
    matchups,
    freeAgents,
    lastSyncedAt: new Date().toISOString(),
    userTeamId,
  };
}

export function createDemoLiveStats(week = 7): LiveStatSnapshot {
  return {
    week,
    updatedAt: new Date().toISOString(),
    games: [
      {
        id: "g1",
        home: "MIA",
        away: "BUF",
        homeScore: 14,
        awayScore: 21,
        status: "in_progress",
        quarter: "Q3",
        clock: "8:42",
      },
      {
        id: "g2",
        home: "GB",
        away: "DET",
        homeScore: 17,
        awayScore: 24,
        status: "in_progress",
        quarter: "Q3",
        clock: "5:11",
      },
      {
        id: "g3",
        home: "DAL",
        away: "NYG",
        homeScore: 20,
        awayScore: 10,
        status: "in_progress",
        quarter: "Q2",
        clock: "2:03",
      },
      {
        id: "g4",
        home: "KC",
        away: "LV",
        homeScore: 0,
        awayScore: 0,
        status: "scheduled",
      },
      {
        id: "g5",
        home: "BAL",
        away: "CIN",
        homeScore: 27,
        awayScore: 24,
        status: "final",
      },
    ],
    topPerformers: [
      { playerName: "Jahmyr Gibbs", position: "RB", points: 21.4, team: "DET" },
      { playerName: "Josh Allen", position: "QB", points: 18.6, team: "BUF" },
      { playerName: "Amon-Ra St. Brown", position: "WR", points: 17.8, team: "DET" },
      { playerName: "CeeDee Lamb", position: "WR", points: 12.3, team: "DAL" },
      { playerName: "Bills D/ST", position: "D/ST", points: 11.0, team: "BUF" },
    ],
  };
}
